CREATE TABLE guestbook (
 id INT(10) NOT NULL AUTO_INCREMENT,
 datetime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
 name VARCHAR(40) NOT NULL DEFAULT '',
 country CHAR(2) NOT NULL DEFAULT '',
 email VARCHAR(80) NOT NULL DEFAULT '',
 comments TEXT NOT NULL DEFAULT '',
 PRIMARY KEY (id));
